#define INPUT 0
#define OUTPUT 1

#define HIGH 1
#define LOW 0

#define CONCAT_8BITS(b7, b6, b5, b4, b3, b2, b1, b0)         \
    (((b7) << 7) | ((b6) << 6) | ((b5) << 5) | ((b4) << 4) | \
     ((b3) << 3) | ((b2) << 2) | ((b1) << 1) | (b0))
/*port A*/
#define PORTA_DIR CONCAT_8BITS(PORTA_PIN7, PORTA_PIN6, PORTA_PIN5, PORTA_PIN4, PORTA_PIN3, PORTA_PIN2, PORTA_PIN1, PORTA_PIN0)
#define PORTA_VALUE CONCAT_8BITS(PORTA_PIN7_VALUE, PORTA_PIN6_VALUE, PORTA_PIN5_VALUE, PORTA_PIN4_VALUE, PORTA_PIN3_VALUE, PORTA_PIN2_VALUE, PORTA_PIN1_VALUE, PORTA_PIN0_VALUE)
#define PORTA_PULLUP CONCAT_8BITS(PORTA_PIN7_PULL, PORTA_PIN6_PULL, PORTA_PIN5_PULL, PORTA_PIN4_PULL, PORTA_PIN3_PULL, PORTA_PIN2_PULL, PORTA_PIN1_PULL, PORTA_PIN0_PULL)

/*port B*/
#define PORTB_DIR CONCAT_8BITS(PORTB_PIN7, PORTB_PIN6, PORTB_PIN5, PORTB_PIN4, PORTB_PIN3, PORTB_PIN2, PORTB_PIN1, PORTB_PIN0)
#define PORTB_VALUE CONCAT_8BITS(PORTB_PIN7_VALUE, PORTB_PIN6_VALUE, PORTB_PIN5_VALUE, PORTB_PIN4_VALUE, PORTB_PIN3_VALUE, PORTB_PIN2_VALUE, PORTB_PIN1_VALUE, PORTB_PIN0_VALUE)
#define PORTB_PULLUP CONCAT_8BITS(PORTB_PIN7_PULL, PORTB_PIN6_PULL, PORTB_PIN5_PULL, PORTB_PIN4_PULL, PORTB_PIN3_PULL, PORTB_PIN2_PULL, PORTB_PIN1_PULL, PORTB_PIN0_PULL)

/* port C*/
#define PORTC_DIR CONCAT_8BITS(PORTC_PIN7, PORTC_PIN6, PORTC_PIN5, PORTC_PIN4, PORTC_PIN3, PORTC_PIN2, PORTC_PIN1, PORTC_PIN0)
#define PORTC_VALUE CONCAT_8BITS(PORTC_PIN7_VALUE, PORTC_PIN6_VALUE, PORTC_PIN5_VALUE, PORTC_PIN4_VALUE, PORTC_PIN3_VALUE, PORTC_PIN2_VALUE, PORTC_PIN1_VALUE, PORTC_PIN0_VALUE)
#define PORTC_PULLUP CONCAT_8BITS(PORTC_PIN7_PULL, PORTC_PIN6_PULL, PORTC_PIN5_PULL, PORTC_PIN4_PULL, PORTC_PIN3_PULL, PORTC_PIN2_PULL, PORTC_PIN1_PULL, PORTC_PIN0_PULL)

/*port D*/
#define PORTD_DIR CONCAT_8BITS(PORTD_PIN7, PORTD_PIN6, PORTD_PIN5, PORTD_PIN4, PORTD_PIN3, PORTD_PIN2, PORTD_PIN1, PORTD_PIN0)
#define PORTD_VALUE CONCAT_8BITS(PORTD_PIN7_VALUE, PORTD_PIN6_VALUE, PORTD_PIN5_VALUE, PORTD_PIN4_VALUE, PORTD_PIN3_VALUE, PORTD_PIN2_VALUE, PORTD_PIN1_VALUE, PORTD_PIN0_VALUE)
#define PORTD_PULLUP CONCAT_8BITS(PORTD_PIN7_PULL, PORTD_PIN6_PULL, PORTD_PIN5_PULL, PORTD_PIN4_PULL, PORTD_PIN3_PULL, PORTD_PIN2_PULL, PORTD_PIN1_PULL, PORTD_PIN0_PULL)

/* PORTA */
/*  DIRECTION */
#define PORTA_PIN0 OUTPUT
#define PORTA_PIN1 OUTPUT
#define PORTA_PIN2 OUTPUT
#define PORTA_PIN3 OUTPUT
#define PORTA_PIN4 INPUT
#define PORTA_PIN5 INPUT
#define PORTA_PIN6 INPUT
#define PORTA_PIN7 INPUT
/* VALUE */
#define PORTA_PIN0_VALUE LOW
#define PORTA_PIN1_VALUE LOW
#define PORTA_PIN2_VALUE LOW
#define PORTA_PIN3_VALUE LOW
#define PORTA_PIN4_VALUE LOW
#define PORTA_PIN5_VALUE LOW
#define PORTA_PIN6_VALUE LOW
#define PORTA_PIN7_VALUE LOW
/* INTERNAL-PULLUP*/
#define PORTA_PIN0_PULL LOW
#define PORTA_PIN1_PULL LOW
#define PORTA_PIN2_PULL LOW
#define PORTA_PIN3_PULL LOW
#define PORTA_PIN4_PULL LOW
#define PORTA_PIN5_PULL LOW
#define PORTA_PIN6_PULL LOW
#define PORTA_PIN7_PULL LOW

/* PORTB */
/*  DIRECTION */
#define PORTB_PIN0 OUTPUT
#define PORTB_PIN1 OUTPUT
#define PORTB_PIN2 OUTPUT
#define PORTB_PIN3 OUTPUT
#define PORTB_PIN4 OUTPUT
#define PORTB_PIN5 OUTPUT
#define PORTB_PIN6 OUTPUT
#define PORTB_PIN7 OUTPUT
/* VALUE */
#define PORTB_PIN0_VALUE LOW
#define PORTB_PIN1_VALUE LOW
#define PORTB_PIN2_VALUE LOW
#define PORTB_PIN3_VALUE LOW
#define PORTB_PIN4_VALUE LOW
#define PORTB_PIN5_VALUE LOW
#define PORTB_PIN6_VALUE LOW
#define PORTB_PIN7_VALUE LOW
/* INTERNAL-PULLUP*/
#define PORTB_PIN0_PULL LOW
#define PORTB_PIN1_PULL LOW
#define PORTB_PIN2_PULL LOW
#define PORTB_PIN3_PULL LOW
#define PORTB_PIN4_PULL LOW
#define PORTB_PIN5_PULL LOW
#define PORTB_PIN6_PULL LOW
#define PORTB_PIN7_PULL LOW

/* PORTC */
/*  DIRECTION */
#define PORTC_PIN0 INPUT
#define PORTC_PIN1 INPUT
#define PORTC_PIN2 INPUT
#define PORTC_PIN3 INPUT
#define PORTC_PIN4 INPUT
#define PORTC_PIN5 INPUT
#define PORTC_PIN6 INPUT
#define PORTC_PIN7 INPUT
/* VALUE */
#define PORTC_PIN0_VALUE LOW
#define PORTC_PIN1_VALUE LOW
#define PORTC_PIN2_VALUE LOW
#define PORTC_PIN3_VALUE LOW
#define PORTC_PIN4_VALUE LOW
#define PORTC_PIN5_VALUE LOW
#define PORTC_PIN6_VALUE LOW
#define PORTC_PIN7_VALUE LOW
/* INTERNAL-PULLUP*/
#define PORTC_PIN0_PULL LOW
#define PORTC_PIN1_PULL LOW
#define PORTC_PIN2_PULL LOW
#define PORTC_PIN3_PULL LOW
#define PORTC_PIN4_PULL LOW
#define PORTC_PIN5_PULL LOW
#define PORTC_PIN6_PULL LOW
#define PORTC_PIN7_PULL LOW

/* PORTD */
/*  DIRECTION */
#define PORTD_PIN0 INPUT
#define PORTD_PIN1 INPUT
#define PORTD_PIN2 INPUT
#define PORTD_PIN3 INPUT
#define PORTD_PIN4 INPUT
#define PORTD_PIN5 INPUT
#define PORTD_PIN6 INPUT
#define PORTD_PIN7 INPUT
/* VALUE */
#define PORTD_PIN0_VALUE LOW
#define PORTD_PIN1_VALUE LOW
#define PORTD_PIN2_VALUE LOW
#define PORTD_PIN3_VALUE LOW
#define PORTD_PIN4_VALUE LOW
#define PORTD_PIN5_VALUE LOW
#define PORTD_PIN6_VALUE LOW
#define PORTD_PIN7_VALUE LOW
/* INTERNAL-PULLUP*/
#define PORTD_PIN0_PULL LOW
#define PORTD_PIN1_PULL LOW
#define PORTD_PIN2_PULL LOW
#define PORTD_PIN3_PULL LOW
#define PORTD_PIN4_PULL LOW
#define PORTD_PIN5_PULL LOW
#define PORTD_PIN6_PULL LOW
#define PORTD_PIN7_PULL LOW